FROM rapidsai/rapidsai:21.08-cuda11.2-base-ubuntu20.04-py3.8

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get autoremove -y
RUN apt-get install -y libsndfile1

WORKDIR /work
# COPY ./src/analyze/ /work/analyze/
COPY ./src/utils/ /work/utils/
COPY ./meta /work/meta

RUN pip install pysoundfile
RUN pip install dcase-util==0.2.18
