ex_name: "sample"
device: "cuda"
base_dir: "/ml"
environments: ".env.mlflow"

result:
  save: false
  vaild_pred_dir: "results"

dataset:
  audio_path: "dataset/audio"
  train_meta: "meta/train_meta_strong.csv"
  valid_meta: "meta/valid_meta_strong.csv"
  test_meta: "meta/test_meta_strong.csv"
  train_weak_label: "meta/train_meta_weak.csv"
  valid_weak_label: "meta/valid_meta_weak.csv"
  test_weak_label: "meta/test_meta_weak.csv"
  train_duration: "meta/train_meta_duration.csv"
  valid_duration: "meta/valid_meta_duration.csv"
  test_duration: "meta/test_meta_duration.csv"
  feat_path: "dataset/feat/mfcc/pretrain-base-ite2-layer-12"
  sr: 16000
  sec: 10
  net_pooling_rate: 1

feature:
  n_filters: 2048
  n_window: 2048
  hop_length: 1024
  f_min: 0
  f_max: 8000
  n_mels: 128

augmentation:
  time_masking:
    time_mask_param: 10
    mask_num: 2
  freq_masking:
    freq_mask_param: 30
    mask_num: 2

training:
  n_epoch: 100
  batch_size: 64
  lr: 0.001
  scheduler: false
  weight_decay: 0.000001
  num_workers: 8
  pin_memory: false
  early_stop_patience: 10
  thresholds: [0.5]
  sed_eval_thr: 0.5

model:
  save: false
  save_path: "models"
  initialize: "default"
  cnn:
    num_layers: 5 # FORGET FIX THIS PARAMETER!!!!
    in_channels: 1
    conv_filters: [128, 128, 128, 128, 128]
    kernel_sizes: [3, 3, 3, 3, 3]
    strides: [1, 1, 1, 1, 1]
    paddings: [1, 1, 1, 1, 1]
    poolings: [[1, 7], [1, 4], [1, 4], [1, 4], [1, 2]]
    dropout_rate: 0.5
  rnn:
    input_size: 128
    hidden_size: 128
    num_layers: 3
    dropout_rate: 0
  dence:
    dropout_rate: 0.5
    out_features: 10

evaluate:
  thresholds:
    [
      0.5,
      0.01,
      0.03,
      0.05,
      0.07,
      0.09,
      0.11,
      0.13,
      0.15,
      0.17,
      0.19,
      0.21,
      0.23,
      0.25,
      0.27,
      0.29,
      0.31,
      0.33,
      0.35,
      0.37,
      0.39,
      0.41,
      0.43,
      0.45,
      0.47,
      0.49,
      0.51,
      0.53,
      0.55,
      0.57,
      0.59,
      0.61,
      0.63,
      0.65,
      0.67,
      0.69,
      0.71,
      0.73,
      0.75,
      0.77,
      0.79,
      0.81,
      0.83,
      0.85,
      0.87,
      0.89,
      0.91,
      0.93,
      0.95,
      0.97,
      0.99,
    ]
  median_filter: 7
  psds:
    val_num: 3
    dtc_thresholds: [0.7, 0.5, 0.1]
    gtc_thresholds: [0.7, 0.5, 0.1]
    cttc_thresholds: [0.3, 0.3, 0.3]
    alpha_cts: [0, 0, 0.5]
    alpha_sts: [1, 0, 1]

defaults:
  - override hydra/sweeper: optuna

hydra:
  run:
    dir: /ml/results/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    storage: null
    # study_name: sed-baseline-lr
    direction: minimize
    n_trials: 100
    n_jobs: 1
    sampler:
      seed: 444
