ex_name: "sample"
device: "cuda"
base_dir: "/ml"
environments: ".env.secret"

result:
  vaild_pred_dir: "results"

dataset:
  audio_path: "dataset/audio"
  train_meta: "meta/train_meta_strong.csv"
  valid_meta: "meta/valid_meta_strong.csv"
  test_meta: "meta/test_meta_strong.csv"
  train_weak_label: "meta/train_meta_weak.csv"
  valid_weak_label: "meta/valid_meta_weak.csv"
  test_weak_label: "meta/test_meta_weak.csv"
  train_duration: "meta/train_meta_duration.csv"
  valid_duration: "meta/valid_meta_duration.csv"
  test_duration: "meta/test_meta_duration.csv"
  sr: 44100
  sec: 10
  net_pooling_rate: 1

feature:
  n_filters: 2048
  n_window: 2048
  hop_length: 1024
  f_min: 50
  f_max: 8000
  n_mels: 128

training:
  n_epoch: 100
  batch_size: 32
  lr: 0.001
  weight_decay: 0
  num_workers: 8
  early_stop_patience: 10
  thresholds: [0.5]
  sed_eval_thr: 0.5

model:
  save_path: "models"
  cnn:
    num_layers: 4 # FORGET FIX THIS PARAMETER!!!!
    in_channels: 1
    conv_filters: [128, 128, 128, 128]
    kernel_sizes: [3, 3, 3, 3]
    strides: [1, 1, 1, 1]
    paddings: [1, 1, 1, 1]
    poolings: [[1, 4], [1, 4], [1, 4], [1, 2]]
    dropout_rate: 0.5
  rnn:
    input_size: 128
    hidden_size: 128
    num_layers: 3
    dropout_rate: 0
  dence:
    dropout_rate: 0.5
    out_features: 10

evaluate:
  thresholds: [0.1, 0.3, 0.5, 0.7, 0.9]
  psds:
    val_num: 3
    dtc_thresholds: [0.7, 0.5, 0.1]
    gtc_thresholds: [0.7, 0.5, 0.1]
    cttc_thresholds: [0.3, 0.3, 0.3]
    alpha_cts: [0, 0, 0.5]
    alpha_sts: [1, 0, 1]
