ex_name: default
device: cuda

dataset:
  audio_path: /path/to/audio
  train_meta: /path/to/train_meta
  valid_meta: /path/to/valid/meta
  test_meta: /path/to/test/meta
  train_weak_label: /path/to/train_weak_label
  valid_weak_label: /path/to/valid_weak_label
  test_weak_label: /path/to/test_weak_label
  train_duration: /path/to/train_duration
  valid_duration: /path/to/valid_duration
  test_duration: /path/to/test_duration
  sr: 44100
  sec: 10
  net_pooling_rate: 1

feature:
  n_filters: 1024
  n_window: 1024
  hop_length: 512
  n_mels: 64

training:
  n_epoch: 100
  batch_size: 16
  lr: 0.001
  weight_decay: 0
  num_workers: 8
  early_stop_patience: 100
  pred_thr: 0.5
  thresholds: [0.5]

model:
  save_path: /path/to/model_save_dir
  cnn:
    num_layers: 3
    in_channels: 1
    conv_filters: [64, 64, 64]
    kernel_sizes: [3, 3, 3]
    strides: [1, 1, 1]
    paddings: [1, 1, 1]
    poolings: [[1, 4], [1, 4], [1, 4]]
    dropout_rate: 0.5
  rnn:
    input_size: 64
    hidden_size: 128
    num_layers: 3
    dropout_rate: 0
  dence:
    dropout_rate: 0.5
    out_features: 10

validation:
  psds:
    val_num: 3
    dtc_thresholds: [0.7, 0.5, 0.1]
    gtc_thresholds: [0.7, 0.5, 0.1]
    cttc_thresholds: [0.3, 0.3, 0.3]
    alpha_cts: [0, 0, 0.5]
    alpha_sts: [1, 0, 1]
