ex_name: finetuing-mfcc
device: cuda
base_dir: /path/to/work_dir
environments: .env.mlflow

result:
  save: false
  vaild_pred_dir: /path/to/result_dir

dataset:
  audio_path: /path/to/audio
  train_meta: /path/to/train_meta
  valid_meta: /path/to/valid/meta
  test_meta: /path/to/test/meta
  train_weak_label: /path/to/train_weak_label
  valid_weak_label: /path/to/valid_weak_label
  test_weak_label: /path/to/test_weak_label
  train_duration: /path/to/train_duration
  valid_duration: /path/to/valid_duration
  test_duration: /path/to/test_duration
  sr: 16000
  sec: 10
  net_pooling_rate: 320

training:
  n_epoch: 100
  batch_size: 2
  lr: 0.001
  scheduler: false
  weight_decay: 0.000001
  num_workers: 8
  pin_memory: false
  early_stop_patience: 10
  thresholds: [0.5]
  sed_eval_thr: 0.5

model:
  save: false
  save_path: /path/to/model_save_dir
  base_model_path: /path/to/pretrained/model/path
  use_layer: 12
  freeze_layer: 11
  cnn:
    num_layers: 4
    in_channels: 1
    conv_filters: [128, 128, 128, 128]
    kernel_sizes: [3, 3, 3, 3]
    strides: [1, 1, 1, 1]
    paddings: [1, 1, 1, 1]
    poolings: [[1, 8], [1, 4], [1, 4], [1, 4]]
    dropout_rate: 0.5
  rnn:
    input_size: 128
    hidden_size: 128
    num_layers: 3
    dropout_rate: 0
  dence:
    dropout_rate: 0.5
    out_features: 10

evaluate:
  thresholds: [0.5]
  median_filter: 7
  psds:
    val_num: 3
    dtc_thresholds: [0.7, 0.5, 0.1]
    gtc_thresholds: [0.7, 0.5, 0.1]
    cttc_thresholds: [0.3, 0.3, 0.3]
    alpha_cts: [0, 0, 0.5]
    alpha_sts: [1, 0, 1]

# defaults:
#   - override hydra/sweeper: optuna

hydra:
  run:
    dir: /path/to/work_dir/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  # sweeper:
  #   storage: null
  #   # study_name: sed-baseline-lr
  #   direction: minimize
  #   n_trials: 100
  #   n_jobs: 1
  #   sampler:
  #     seed: 444
