ex_name: "sample"
device: "cuda"

dataset:
  audio_path: "/ml/dataset/audio"
  train_meta: "/ml/meta/train_meta_strong.csv"
  valid_meta: "/ml/meta/valid_meta_strong.csv"
  test_meta: "/ml/meta/test_meta_strong.csv"
  train_weak_label: "/ml/meta/train_meta_weak.csv"
  valid_weak_label: "/ml/meta/valid_meta_weak.csv"
  test_weak_label: "/ml/meta/test_meta_weak.csv"
  train_duration: "/ml/meta/train_meta_duration.csv"
  valid_duration: "/ml/meta/valid_meta_duration.csv"
  test_duration: "/ml/meta/test_meta_duration.csv"
  sr: 44100
  sec: 10
  net_pooling_rate: 1

feature:
  n_filters: 2048
  n_window: 2048
  hop_length: 1024
  n_mels: 128

training:
  n_epoch: 100
  batch_size: 32
  lr: 0.001
  num_workers: 8
  early_stop_patience: 10
  pred_thr: 0.5
  thresholds: [0.5]

model:
  save_path: "/ml/models"
  cnn:
    num_layers: 4
    in_channels: 1
    conv_filters: [128, 128, 128, 128]
    kernel_sizes: [3, 3, 3, 3]
    strides: [1, 1, 1, 1]
    paddings: [1, 1, 1, 1]
    poolings: [[1, 4], [1, 4], [1, 4], [1, 2]]
    dropout_rate: 0.5
  rnn:
    input_size: 128
    hidden_size: 128
    num_layers: 3
    dropout_rate: 0
  dence:
    dropout_rate: 0.5
    out_features: 10

validation:
  psds:
    val_num: 3
    dtc_thresholds: [0.7, 0.5, 0.1]
    gtc_thresholds: [0.7, 0.5, 0.1]
    cttc_thresholds: [0.3, 0.3, 0.3]
    alpha_cts: [0, 0, 0.5]
    alpha_sts: [1, 0, 1]
