ex_name: "sample-hubert"
device: "cuda"

result:
  vaild_pred_dir: "/ml/results"

dataset:
  audio_path: "/ml/dataset/audio"
  train_meta: "/ml/meta/train_meta_strong.csv"
  valid_meta: "/ml/meta/valid_meta_strong.csv"
  test_meta: "/ml/meta/test_meta_strong.csv"
  train_weak_label: "/ml/meta/train_meta_weak.csv"
  valid_weak_label: "/ml/meta/valid_meta_weak.csv"
  test_weak_label: "/ml/meta/test_meta_weak.csv"
  train_duration: "/ml/meta/train_meta_duration.csv"
  valid_duration: "/ml/meta/valid_meta_duration.csv"
  test_duration: "/ml/meta/test_meta_duration.csv"
  feat_path: "/ml/dataset/feat/libri-base-layer-12"
  sr: 16000
  sec: 10
  net_pooling_rate: 320

training:
  n_epoch: 100
  batch_size: 8
  lr: 0.001
  num_workers: 8
  early_stop_patience: 10
  thresholds: [0.5]
  sed_eval_thr: 0.5

model:
  save_path: "/ml/models"
  cnn:
    num_layers: 3 # FORGET FIX THIS PARAMETER!!!!
    in_channels: 1
    conv_filters: [128, 128, 128]
    kernel_sizes: [3, 3, 3]
    strides: [1, 1, 1]
    paddings: [1, 1, 1]
    poolings: [[1, 8], [1, 8], [1, 8]]
    dropout_rate: 0.5
  rnn:
    input_size: 128
    hidden_size: 128
    num_layers: 3
    dropout_rate: 0
  dence:
    dropout_rate: 0.5
    out_features: 10

evaluate:
  thresholds: [0.1, 0.3, 0.5, 0.7, 0.9]
  psds:
    val_num: 3
    dtc_thresholds: [0.7, 0.5, 0.1]
    gtc_thresholds: [0.7, 0.5, 0.1]
    cttc_thresholds: [0.3, 0.3, 0.3]
    alpha_cts: [0, 0, 0.5]
    alpha_sts: [1, 0, 1]
